name: CI/CD Pipeline for Memoir Application - Backend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Change Directory, Pull Changes, and Install Dependencies
        run: |
          cd ./memoir-backend  
          npm install

      # - name: Build and Test
      #   run: |
      #     cd ./memoir-backend  
      #     npm run build

      # - name: Save npm debug logs
      #   if: always()
      #   run: |
      #      mkdir -p $GITHUB_WORKSPACE/logs
      #      ls /home/runner/.npm/_logs/
      #      cp /home/runner/.npm/_logs/*.log $GITHUB_WORKSPACE/logs/
      #      echo "Logs saved in $GITHUB_WORKSPACE/logs/"

      # - name: Upload logs artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: npm-logs
      #     path: $GITHUB_WORKSPACE/logs

  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build and Push to DockerHub
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{secrets.DOCKER_REPOSITORY}}:memoir-frontend-reactjs-app-latest

      # - name: Upload log artifacts
      #   if: always()
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: logs
      #     path: $GITHUB_WORKSPACE/logs
